### ISSUE TITLE
Redirects yield Server Errors

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt/nitro-demo#32]
Using { redirect } from context inside middleware or asyncData yields a server error

```
Cannot set headers after they are sent to the client
  at ServerResponse.setHeader (_http_outgoing.js:518:11)  
  at renderMiddleware (./node_modules/@nuxt/nitro/dist/runtime/app/render.mjs:53:9)  
  at processTicksAndRejections (internal/process/task_queues.js:97:5)  
  at handle2 (./node_modules/h3/dist/index.js:558:19)
```
```
<template>
    <div>hi</div>
</template>
<script>
export default {
    middleware({ redirect }){
        redirect('/no-access')
    },
}
</script>
```

**Comment by pi0** [comment]
Fixed by https://github.com/nuxt/framework/pull/392
